program Comple_Test;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Z.AES in '..\Source\Z.AES.pas',
  Z.BulletMovementEngine in '..\Source\Z.BulletMovementEngine.pas',
  Z.Cadencer in '..\Source\Z.Cadencer.pas',
  Z.Cipher in '..\Source\Z.Cipher.pas',
  Z.Compress in '..\Source\Z.Compress.pas',
  Z.Core in '..\Source\Z.Core.pas',
  Z.Delphi.JsonDataObjects in '..\Source\Z.Delphi.JsonDataObjects.pas',
  Z.DFE in '..\Source\Z.DFE.pas',
  Z.Expression in '..\Source\Z.Expression.pas',
  Z.FastGBK in '..\Source\Z.FastGBK.pas',
  Z.FPC.GenericList in '..\Source\Z.FPC.GenericList.pas',
  Z.FragmentBuffer in '..\Source\Z.FragmentBuffer.pas',
  Z.GBK in '..\Source\Z.GBK.pas',
  Z.GBKBig in '..\Source\Z.GBKBig.pas',
  Z.GBKMediaCenter in '..\Source\Z.GBKMediaCenter.pas',
  Z.GBKVec in '..\Source\Z.GBKVec.pas',
  Z.Geometry.Low in '..\Source\Z.Geometry.Low.pas',
  Z.Geometry.Rotation in '..\Source\Z.Geometry.Rotation.pas',
  Z.Geometry2D in '..\Source\Z.Geometry2D.pas',
  Z.Geometry3D in '..\Source\Z.Geometry3D.pas',
  Z.HashHours.Templet in '..\Source\Z.HashHours.Templet.pas',
  Z.HashList.Templet in '..\Source\Z.HashList.Templet.pas',
  Z.HashMinutes.Templet in '..\Source\Z.HashMinutes.Templet.pas',
  Z.IOThread in '..\Source\Z.IOThread.pas',
  Z.Json in '..\Source\Z.Json.pas',
  Z.Line2D.Templet in '..\Source\Z.Line2D.Templet.pas',
  Z.LinearAction in '..\Source\Z.LinearAction.pas',
  Z.ListEngine in '..\Source\Z.ListEngine.pas',
  Z.Matched.Templet in '..\Source\Z.Matched.Templet.pas',
  Z.MD5 in '..\Source\Z.MD5.pas',
  Z.MediaCenter in '..\Source\Z.MediaCenter.pas',
  Z.MemoryStream in '..\Source\Z.MemoryStream.pas',
  Z.MH in '..\Source\Z.MH.pas',
  Z.MH_ZDB in '..\Source\Z.MH_ZDB.pas',
  Z.MH1 in '..\Source\Z.MH1.pas',
  Z.MH2 in '..\Source\Z.MH2.pas',
  Z.MH3 in '..\Source\Z.MH3.pas',
  Z.MovementEngine in '..\Source\Z.MovementEngine.pas',
  Z.Net.C4 in '..\Source\Z.Net.C4.pas',
  Z.Net.C4.VM in '..\Source\Z.Net.C4.VM.pas',
  Z.Net.C4.VM_FS2 in '..\Source\Z.Net.C4.VM_FS2.pas',
  Z.Net.C4.VM_TEKeyValue in '..\Source\Z.Net.C4.VM_TEKeyValue.pas',
  Z.Net.C4.VM_Var in '..\Source\Z.Net.C4.VM_Var.pas',
  Z.Net.C4_Alias in '..\Source\Z.Net.C4_Alias.pas',
  Z.Net.C4_Console_APP in '..\Source\Z.Net.C4_Console_APP.pas',
  Z.Net.C4_FS in '..\Source\Z.Net.C4_FS.pas',
  Z.Net.C4_FS2 in '..\Source\Z.Net.C4_FS2.pas',
  Z.Net.C4_Log_DB in '..\Source\Z.Net.C4_Log_DB.pas',
  Z.Net.C4_NetDisk_Admin_Tool in '..\Source\Z.Net.C4_NetDisk_Admin_Tool.pas',
  Z.Net.C4_NetDisk_Client in '..\Source\Z.Net.C4_NetDisk_Client.pas',
  Z.Net.C4_NetDisk_Client.Task in '..\Source\Z.Net.C4_NetDisk_Client.Task.pas',
  Z.Net.C4_NetDisk_Directory in '..\Source\Z.Net.C4_NetDisk_Directory.pas',
  Z.Net.C4_NetDisk_Service in '..\Source\Z.Net.C4_NetDisk_Service.pas',
  Z.Net.C4_NetDisk_VM_Client in '..\Source\Z.Net.C4_NetDisk_VM_Client.pas',
  Z.Net.C4_NetDisk_VM_Client.Task in '..\Source\Z.Net.C4_NetDisk_VM_Client.Task.pas',
  Z.Net.C4_NetDisk_VM_Service in '..\Source\Z.Net.C4_NetDisk_VM_Service.pas',
  Z.Net.C4_PascalRewrite_Client in '..\Source\Z.Net.C4_PascalRewrite_Client.pas',
  Z.Net.C4_PascalRewrite_Service in '..\Source\Z.Net.C4_PascalRewrite_Service.pas',
  Z.Net.C4_RandSeed in '..\Source\Z.Net.C4_RandSeed.pas',
  Z.Net.C4_TEKeyValue in '..\Source\Z.Net.C4_TEKeyValue.pas',
  Z.Net.C4_UserDB in '..\Source\Z.Net.C4_UserDB.pas',
  Z.Net.C4_Var in '..\Source\Z.Net.C4_Var.pas',
  Z.Net.C4_VM_RandSeed in '..\Source\Z.Net.C4_VM_RandSeed.pas',
  Z.Net.C4_VM_UserDB in '..\Source\Z.Net.C4_VM_UserDB.pas',
  Z.Net.C4_XNAT in '..\Source\Z.Net.C4_XNAT.pas',
  Z.Net.DataStoreService.Common in '..\Source\Z.Net.DataStoreService.Common.pas',
  Z.Net.DataStoreService.NoAuth in '..\Source\Z.Net.DataStoreService.NoAuth.pas',
  Z.Net.DataStoreService in '..\Source\Z.Net.DataStoreService.pas',
  Z.Net.DataStoreService.VirtualAuth in '..\Source\Z.Net.DataStoreService.VirtualAuth.pas',
  Z.Net.DoubleTunnelIO.NoAuth in '..\Source\Z.Net.DoubleTunnelIO.NoAuth.pas',
  Z.Net.DoubleTunnelIO in '..\Source\Z.Net.DoubleTunnelIO.pas',
  Z.Net.DoubleTunnelIO.ServMan in '..\Source\Z.Net.DoubleTunnelIO.ServMan.pas',
  Z.Net.DoubleTunnelIO.VirtualAuth in '..\Source\Z.Net.DoubleTunnelIO.VirtualAuth.pas',
  Z.Net.IO in '..\Source\Z.Net.IO.pas',
  Z.Net in '..\Source\Z.Net.pas',
  Z.Net.PhysicsIO in '..\Source\Z.Net.PhysicsIO.pas',
  Z.Net.Test in '..\Source\Z.Net.Test.pas',
  Z.Net.XNAT.Client in '..\Source\Z.Net.XNAT.Client.pas',
  Z.Net.XNAT.MappingOnVirutalService in '..\Source\Z.Net.XNAT.MappingOnVirutalService.pas',
  Z.Net.XNAT.Physics in '..\Source\Z.Net.XNAT.Physics.pas',
  Z.Net.XNAT.Service in '..\Source\Z.Net.XNAT.Service.pas',
  Z.Notify in '..\Source\Z.Notify.pas',
  Z.Number in '..\Source\Z.Number.pas',
  Z.OpCode in '..\Source\Z.OpCode.pas',
  Z.Parsing in '..\Source\Z.Parsing.pas',
  Z.Pascal_Code_Tool in '..\Source\Z.Pascal_Code_Tool.pas',
  Z.Pascal_Rewrite_Model_Data in '..\Source\Z.Pascal_Rewrite_Model_Data.pas',
  Z.PascalStrings in '..\Source\Z.PascalStrings.pas',
  Z.Status in '..\Source\Z.Status.pas',
  Z.TextDataEngine in '..\Source\Z.TextDataEngine.pas',
  Z.TextTable in '..\Source\Z.TextTable.pas',
  Z.UnicodeMixedLib in '..\Source\Z.UnicodeMixedLib.pas',
  Z.UPascalStrings in '..\Source\Z.UPascalStrings.pas',
  Z.UReplace in '..\Source\Z.UReplace.pas',
  Z.ZDB.Engine in '..\Source\Z.ZDB.Engine.pas',
  Z.ZDB.FileIndexPackage_LIB in '..\Source\Z.ZDB.FileIndexPackage_LIB.pas',
  Z.ZDB.FilePackage_LIB in '..\Source\Z.ZDB.FilePackage_LIB.pas',
  Z.ZDB.HashField_LIB in '..\Source\Z.ZDB.HashField_LIB.pas',
  Z.ZDB.HashItem_LIB in '..\Source\Z.ZDB.HashItem_LIB.pas',
  Z.ZDB.ItemStream_LIB in '..\Source\Z.ZDB.ItemStream_LIB.pas',
  Z.ZDB.LocalManager in '..\Source\Z.ZDB.LocalManager.pas',
  Z.ZDB.ObjectData_LIB in '..\Source\Z.ZDB.ObjectData_LIB.pas',
  Z.ZDB in '..\Source\Z.ZDB.pas',
  Z.ZDB2.DFE in '..\Source\Z.ZDB2.DFE.pas',
  Z.ZDB2.FileEncoder in '..\Source\Z.ZDB2.FileEncoder.pas',
  Z.ZDB2.HS in '..\Source\Z.ZDB2.HS.pas',
  Z.ZDB2.HV in '..\Source\Z.ZDB2.HV.pas',
  Z.ZDB2.Json in '..\Source\Z.ZDB2.Json.pas',
  Z.ZDB2.MEM64 in '..\Source\Z.ZDB2.MEM64.pas',
  Z.ZDB2.MS64 in '..\Source\Z.ZDB2.MS64.pas',
  Z.ZDB2.NM in '..\Source\Z.ZDB2.NM.pas',
  Z.ZDB2.ObjectDataManager in '..\Source\Z.ZDB2.ObjectDataManager.pas',
  Z.ZDB2 in '..\Source\Z.ZDB2.pas',
  Z.ZDB2.TE in '..\Source\Z.ZDB2.TE.pas',
  Z.ZDB2.Thread.APP in '..\Source\Z.ZDB2.Thread.APP.pas',
  Z.ZDB2.Thread.LargeData in '..\Source\Z.ZDB2.Thread.LargeData.pas',
  Z.ZDB2.Thread.Pair_MD5_Stream in '..\Source\Z.ZDB2.Thread.Pair_MD5_Stream.pas',
  Z.ZDB2.Thread.Pair_String_Stream in '..\Source\Z.ZDB2.Thread.Pair_String_Stream.pas',
  Z.ZDB2.Thread in '..\Source\Z.ZDB2.Thread.pas',
  Z.ZDB2.Thread.Queue in '..\Source\Z.ZDB2.Thread.Queue.pas';

begin
  try
    { TODO -oUser -cConsole Main : Insert code here }
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
