// Compatible Define

(*
type
  TCoreClassPersistent = TCore_Persistent;
  TCoreClassFileStream = TCore_FileStream;
  TCoreClassStringStream = TCore_StringStream;
  TCoreClassResourceStream = TCore_ResourceStream;
  TCoreClassMemoryStream = TCore_MemoryStream;
  TCoreClassStrings = TCore_Strings;
  TCoreClassStringList = TCore_StringList;
  TCoreClassReader = TCore_Reader;
  TCoreClassWriter = TCore_Writer;
  TCoreClassComponent = TCore_Component;
{$IFDEF FPC}
  TCoreClassListSortCompare = TCore_ListSortCompare;
  TCoreClassListNotification = TCore_ListNotification;
{$ENDIF FPC}
  TCoreClassPointerList = TCore_PointerList;
  TCoreClassForObjectList = TCore_ForObjectList;
  TCoreClassStream = TCore_Stream;
  TCoreClassInterfacedObject = TCore_InterfacedObject;
  TCoreClassList = TCore_List;
  TCoreClassListForObj = TCore_ListForObj;
  TCoreClassObject = TCore_Object;
  TCoreClassObjectList = TCore_ObjectList;
  TCoreClassThread = TCore_Thread;
*)

